name: Label Commenter

on:
  issues:
    types:
      - labeled
      - unlabeled

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Label Commenter
        uses: peaceiris/actions-label-commenter@f0dbbef043eb1b150b566db36b0bdc8b7f505579
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          config_file: .github/configs/label-commenter-config.yml
